### ISSUE TITLE
OLED module PINs

### ISSUE THREAD

**Issue by DooMMasteR** [hallard/WeMos-Lora#12]
The order seems a bit weird, 99% of the cheap modules have the pin in the order

```GND Vcc SCL SDA```

and not 

```Vcc GND SCL SDA```

as on the your PCB

**Comment by hallard** [comment]
You're right, but when I created the board 90% of OLED was in this order, after that we had OLED price going up then again down, and I saw they have switched the pin, don't know why they do that but was not a good idea ;-)
that's why on new boards I make you can revert vcc/gnd by solder pad, I need to update this one

**Comment by hallard** [comment]
Fixed in V1.3
