### ISSUE TITLE
Bill of materials

### ISSUE THREAD

**Issue by jpmeijers** [hallard/WeMos-Lora#14]
Please add a list of components needed to populate this board. I was unaware that I needed 3 diodes to get it in a usable state. I am also still unsure which exact component the diodes should be. Are they 0805?

* Number (ex. D1, R3)
* Value (ex. 1N4148, 10K)
* Footprint/size (ex. 0805)
* A link to a source for the component

**Comment by hallard** [comment]
@jpmeijers 
As indicated in the readme, diodes are not mandatory is you use my LMIC fork. 
If not, then you need to solder them. Since schematics and board files are in the repo I thought it was easy to find these informations about components. But I was wrong, sorry.

So here is the [octopart BOM](https://octopart.com/bom-tool/SJPhS5Am) file, I've updated to ReadMe to add this link

Thanks for pointing it out.
